# Generated by Django 5.2 on 2025-05-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('laboratorio', models.CharField(max_length=100)),
                ('dosis', models.TextField()),
                ('presentacion', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=100)),
                ('caducidad', models.CharField(max_length=100)),
            ],
        ),
    ]
