# Generated by Django 5.2 on 2025-05-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('consultorio', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('licencia', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=15)),
            ],
        ),
    ]
