# Generated by Django 5.2 on 2025-05-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remitente', models.CharField(max_length=100)),
                ('destinatario', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=100)),
                ('asunto', models.CharField(max_length=100)),
            ],
        ),
    ]
